#!/bin/bash
# Download scholar.bib (most recent publications should be enough).
# Put it in $data
function bib(){
    cd ~/github/abhijin.github.io/work/
    python ../scripts/papers.py scholar2db
}

# Generate files for CV
function cv(){
    cd ~/github/abhijin.github.io/cv
    python ../scripts/papers.py db2cv
}

# Compile CV in cv/cv_abhijin.tex

function web(){
    cd ~/github/abhijin.github.io/
    python scripts/papers.py db2html
    cat intro.html.part papers.html.part end.html.part > index.html 
}

if [[ $# == 0 ]]; then
   echo "Here are the options:"
   grep "^function" $BASH_SOURCE | sed -e 's/function/  /' -e 's/[(){]//g' -e '/IGNORE/d'
else
   eval $1 $2 $3 $4
fi